import Link from "next/link";
import type { ReactElement } from "react";

import { PageContent } from "@/components/layout/page-content";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { StatusToast } from "@/components/ui/status-toast";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { BrochureExportStatusBadge } from "@/features/brochures/components/brochure-export-status-badge";
import {
  BROCHURE_EXPORT_STATUS_FILTER_OPTIONS,
  BROCHURE_EXPORT_TYPE_FILTER_OPTIONS,
} from "@/features/brochures/constants";
import { getBrochureExports } from "@/features/brochures/queries";
import { getBrochureExportTypeLabel } from "@/features/brochures/utils";
import { formatCrmDateTime } from "@/features/inquiries/utils";
import { getAdminAccessContext } from "@/lib/auth/session";

type BrochuresPageProps = {
  searchParams: Promise<{
    error?: string | string[];
    exportType?: string | string[];
    status?: string | string[];
    success?: string | string[];
  }>;
};

function getSearchParam(
  value: string | string[] | undefined,
): string | undefined {
  return Array.isArray(value) ? value[0] : value;
}

export default async function BrochuresPage({
  searchParams,
}: BrochuresPageProps): Promise<ReactElement | null> {
  const access = await getAdminAccessContext();

  if (!access) {
    return null;
  }

  const resolvedSearchParams = await searchParams;
  const error = getSearchParam(resolvedSearchParams.error);
  const success = getSearchParam(resolvedSearchParams.success);
  const result = await getBrochureExports(access, resolvedSearchParams);

  return (
    <>
      <StatusToast message={error} variant="error" />
      <StatusToast message={success} variant="success" />

      <PageContent
        title="Brochures"
        description="Generate and download vehicle PDFs for one unit or a curated selection."
        actions={
          <>
            <Button asChild variant="outline">
              <Link href="/admin/vehicles">Vehicles</Link>
            </Button>
            <Button asChild>
              <Link href="/admin/brochures/new">Create Brochure</Link>
            </Button>
          </>
        }
      >
        <form className="grid gap-3 rounded-[20px] border border-border bg-white p-4 lg:grid-cols-[240px_240px_auto_auto]">
          <Select defaultValue={result.filters.exportType} name="exportType">
            {BROCHURE_EXPORT_TYPE_FILTER_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </Select>

          <Select defaultValue={result.filters.status} name="status">
            {BROCHURE_EXPORT_STATUS_FILTER_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </Select>

          <Button type="submit" variant="outline">
            Apply
          </Button>
          <Button asChild variant="ghost">
            <Link href="/admin/brochures">Reset</Link>
          </Button>
        </form>

        {result.exports.length === 0 ? (
          <div className="rounded-[20px] border border-dashed border-border bg-white px-6 py-12 text-center">
            <p className="text-sm font-semibold text-foreground">
              No brochures generated yet
            </p>
            <p className="mt-1 text-sm text-muted-foreground">
              Create the first brochure from a vehicle detail page or the brochure generator.
            </p>
          </div>
        ) : (
          <>
            <div className="overflow-hidden rounded-[20px] border border-border bg-white">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead>Title</TableHead>
                    <TableHead>Export Type</TableHead>
                    <TableHead>Vehicles Included</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Generated Date</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {result.exports.map((exportRow) => {
                    const firstVehicle = exportRow.vehicles[0] ?? null;

                    return (
                      <TableRow key={exportRow.id}>
                        <TableCell className="align-top">
                          <div className="space-y-1">
                            <p className="font-medium text-foreground">
                              {exportRow.title || "Untitled brochure"}
                            </p>
                            {exportRow.error_message ? (
                              <p className="text-xs text-red-700">
                                {exportRow.error_message}
                              </p>
                            ) : null}
                          </div>
                        </TableCell>
                        <TableCell className="align-top text-muted-foreground">
                          {getBrochureExportTypeLabel(exportRow.export_type)}
                        </TableCell>
                        <TableCell className="align-top">
                          <div className="space-y-1">
                            <p className="text-sm text-foreground">
                              {exportRow.vehicles
                                .slice(0, 2)
                                .map((vehicle) => vehicle.title)
                                .join(", ")}
                            </p>
                            {exportRow.vehicles.length > 2 ? (
                              <p className="text-xs text-muted-foreground">
                                +{exportRow.vehicles.length - 2} more vehicles
                              </p>
                            ) : null}
                          </div>
                        </TableCell>
                        <TableCell className="align-top">
                          <BrochureExportStatusBadge status={exportRow.status} />
                        </TableCell>
                        <TableCell className="align-top text-muted-foreground">
                          {exportRow.generatedByName ?? "Team member"}
                        </TableCell>
                        <TableCell className="align-top text-muted-foreground">
                          {exportRow.generated_at
                            ? formatCrmDateTime(exportRow.generated_at)
                            : formatCrmDateTime(exportRow.created_at)}
                        </TableCell>
                        <TableCell className="align-top">
                          <div className="flex justify-end gap-2">
                            {exportRow.status === "generated" ? (
                              <Button asChild size="sm" variant="outline">
                                <Link href={`/api/brochures/${exportRow.id}/download`}>
                                  Download
                                </Link>
                              </Button>
                            ) : null}

                            {firstVehicle ? (
                              <Button asChild size="sm" variant="outline">
                                <Link href={`/admin/vehicles/${firstVehicle.id}`}>
                                  Vehicle
                                </Link>
                              </Button>
                            ) : null}
                          </div>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>

            <div className="px-1 text-sm text-muted-foreground">
              Showing {result.exports.length} of {result.totalCount}
            </div>
          </>
        )}
      </PageContent>
    </>
  );
}
